version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: golfclub
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/golfclub
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password
        SPRING_DATASOURCE_URL: jdbc:mysql://golfclub-db.corqv6hasing.us-east-1.rds.amazonaws.com:3306/golfclub
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: Password123
volumes:
  mysql_data: